kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-chronicle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-chronicle
  template:
    metadata:
      labels:
        app: frontend-chronicle
    spec:
      containers:
        - name: frontend-chronicle
          image: localhost:5000/frontend-chronicle
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-chronicle
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: frontend-chronicle