version: '3.7'

services:

  sample:
    tty: true
    stdin_open: true
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ENV=development
      - REACT_APP_DEV_GRAPH_API=http://backend:3001/graphql
      - BACKEND_PORT=3001
